export const BOOKING_STATUS_VALUE = {
  REQUESTED: 'requested',
  EXPIRED: 'expired',
  DECLINED: 'declined',
  ACCEPTED_PENDING_PAYMENT: 'accepted_pending_payment',
  PAID_CONFIRMED: 'paid_confirmed',
  ON_THE_WAY: 'on_the_way',
  ARRIVED: 'arrived',
  COMPLETED_BY_BARBER: 'completed_by_barber',
  COMPLETED_BY_CLIENT: 'completed_by_client',
  COMPLETION_PROMPT_SENT: 'completion_prompt_sent',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  DISPUTED: 'disputed',
  REFUNDED: 'refunded',
  ADMIN_RESOLVED: 'admin_resolved',
} as const;

export const BOOKING_STATUS = [
  BOOKING_STATUS_VALUE.REQUESTED,
  BOOKING_STATUS_VALUE.EXPIRED,
  BOOKING_STATUS_VALUE.DECLINED,
  BOOKING_STATUS_VALUE.ACCEPTED_PENDING_PAYMENT,
  BOOKING_STATUS_VALUE.PAID_CONFIRMED,
  BOOKING_STATUS_VALUE.ON_THE_WAY,
  BOOKING_STATUS_VALUE.ARRIVED,
  BOOKING_STATUS_VALUE.COMPLETED_BY_BARBER,
  BOOKING_STATUS_VALUE.COMPLETED_BY_CLIENT,
  BOOKING_STATUS_VALUE.COMPLETION_PROMPT_SENT,
  BOOKING_STATUS_VALUE.COMPLETED,
  BOOKING_STATUS_VALUE.CANCELLED,
  BOOKING_STATUS_VALUE.DISPUTED,
  BOOKING_STATUS_VALUE.REFUNDED,
  BOOKING_STATUS_VALUE.ADMIN_RESOLVED,
] as const;

export type BookingStatus = (typeof BOOKING_STATUS)[number];
